### PR TITLE
Update for Nomad Variables

### PR DESCRIPTION
**Pull request by tgross**
Ready for review. I'll do a follow-up for Keyring once this has been merged so that I'm not reworking both with the same comments emerging from any misunderstanding I have of what I'm supposed to be doing here. 😀 

There's a few bits in the [generator README](https://github.com/hashicorp/nomad-openapi/blob/main/generator/README.md) that don't appear to be up-to-date, and I'm not sure if those are just not a problem anymore or if I'm got something silently failing:
* The number of operations per path doesn't appear to be really capped at 3.
* PUT being deprecated for POST isn't something that's happening in the v1 Nomad API as far as I've seen.
* I'm not sure what a "test client" is but it doesn't seem to be referred to anywhere else in that doc other than at the end.

Also, what's the expectations around the "higher level API" package here? I've done some spot checks and it doesn't actually look higher-level to me.

### CODE REVIEW

**Comment by tgross** [comment]
Needed to update the test runner for the following error:

```
📦 github.com/hashicorp/nomad/helper/pool
Error: ../../../../go/pkg/mod/github.com/hashicorp/nomad@v1.4.0-beta.1/helper/pool/pool.go:50:18: undefined: atomic.Pointer
Error: ../../../../go/pkg/mod/github.com/hashicorp/nomad@v1.4.0-beta.1/helper/pool/pool.go:406:20: undefined: atomic.Pointer
note: module requires Go 1.19
```

**Comment by DerekStrickland** [comment]
> There's a few bits in the [generator README](https://github.com/hashicorp/nomad-openapi/blob/main/generator/README.md) that don't appear to be up-to-date, and I'm not sure if those are just not a problem anymore or if I'm got something silently failing:
> 
> * The number of operations per path doesn't appear to be really capped at 3.

Yeah, it's a convention-based cap which I tried to explain in the next sentence. I'll reword that to make it more clear. 

> * PUT being deprecated for POST isn't something that's happening in the v1 Nomad API as far as I've seen.

This was another _convention based_ thing in _this package_ based on the observation I believed at the time as stated in this line. 

"While it is true, that the POST endpoint handlers will typically support PUT, our online documentation only documents our support for POST. "

However, a deeper search a year later has led me to find a small number of cases where the HTTP API docs actually do document support for `PUT`. I think that `PUT` is probably the right method since it represents an upsert, but at the time, all the docs I reviewed only documented `POST` even though the actual code supported both. So in an effort to standardize on one, I went that way.  

> * I'm not sure what a "test client" is but it doesn't seem to be referred to anywhere else in that doc other than at the end.

Heh, reading whole explanation that a year later it's not very good. :( That paragraph is about the [service layer](https://github.com/hashicorp/nomad-openapi/tree/main/v1) I built on top of the generated code. I'll update that language and add links to make it more user friendly. 

> Also, what's the expectations around the "higher level API" package here? I've done some spot checks and it doesn't actually look higher-level to me.

See the service layer comments above. I'm going to approve this request in case it's blocking you, but it might be good to pair on the implementation of the service layer part and include in this PR.  I think it would give us a good chance to real time review that, and just generally sync on this repo.

**Review by DerekStrickland — APPROVED** [review]
See response to comments.  I'm approving now in case it's blocking you.

**Comment by tgross** [comment]
> Yeah, it's a convention-based cap (snip)

We can chat about this at our group meeting next week but given that we're not (yet) using this repo as the source of truth, we should avoid trying to set behavioral conventions from this repo; the Nomad API is the source of truth and sets the behavior and this repo should follow.

> See the service layer comments above. I'm going to approve this request in case it's blocking you, but it might be good to pair on the implementation of the service layer part and include in this PR. I think it would give us a good chance to real time review that, and just generally sync on this repo.

Given the _current_ direction of flow I'm not sure the service layer makes a lot of sense. We can chat about that next week too. Either way, this PR is already a massive 15k lines because of all the client updates, so given your approval I'm going to just merge this as-is and we can come back to that.

**Pull request merged**
